# -*- coding: utf-8 -*-
"""Broker-neutral risk-management contracts for LGE Runtime."""

from engine.risk.constants import (
    RISK_DECISION_ALLOW,
    RISK_DECISION_BLOCK,
    RISK_REASON_ACCOUNT_BINDING_MISMATCH,
    RISK_REASON_ACCOUNT_SNAPSHOT_MISSING,
    RISK_REASON_APPROVED,
    RISK_REASON_DAILY_LOSS_LIMIT_REACHED,
    RISK_REASON_INVALID_LOSS_AT_STOP,
    RISK_REASON_MARKET_INVALID,
    RISK_REASON_MAXIMUM_OPEN_POSITIONS_REACHED,
    RISK_REASON_MAXIMUM_POSITION_VOLUME_EXCEEDED,
    RISK_REASON_RISK_PERCENT_EXCEEDED,
    RISK_REASON_RUNTIME_NOT_READY,
    RISK_REASON_SPREAD_BLOCKED,
    RISK_REASON_STOP_LOSS_REQUIRED,
)
from engine.risk.risk_model import (
    WorkspaceRiskDecision,
    WorkspaceRiskEvaluator,
    WorkspaceRiskPolicy,
    WorkspaceRiskRequest,
)

__all__ = (
    "RISK_DECISION_ALLOW",
    "RISK_DECISION_BLOCK",
    "RISK_REASON_ACCOUNT_BINDING_MISMATCH",
    "RISK_REASON_ACCOUNT_SNAPSHOT_MISSING",
    "RISK_REASON_APPROVED",
    "RISK_REASON_DAILY_LOSS_LIMIT_REACHED",
    "RISK_REASON_INVALID_LOSS_AT_STOP",
    "RISK_REASON_MARKET_INVALID",
    "RISK_REASON_MAXIMUM_OPEN_POSITIONS_REACHED",
    "RISK_REASON_MAXIMUM_POSITION_VOLUME_EXCEEDED",
    "RISK_REASON_RISK_PERCENT_EXCEEDED",
    "RISK_REASON_RUNTIME_NOT_READY",
    "RISK_REASON_SPREAD_BLOCKED",
    "RISK_REASON_STOP_LOSS_REQUIRED",
    "WorkspaceRiskDecision",
    "WorkspaceRiskEvaluator",
    "WorkspaceRiskPolicy",
    "WorkspaceRiskRequest",
)
